# 외부 DB 설정시 아래의 주석을 활성화 시킨 후 관련 DB 설정 정보를 입력한다.
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password:

server:
  port: 8080
  session:
    cookie:
      name: APPSESSIONID

spring.h2.console:
  enabled: true
  path: /h2-console

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ssotest?serverTimezone=Asia/Seoul&useSSL=false
#    username: root
#    password: 1234
#    initialization-model: always
#  jpa:
#    hibernate:
#      ddl-auto: create-drop or true
#      show-sql: true






spring:
  profiles: version1
  datasource:
    url: jdbc:h2:mem://localhost/~/ssotest;MVCC=TRUE
    username: root
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: true
      show-sql: true
      properties.hibernate.format_sql: true


logging.level:
  root: warn
  org.springframework:
    web: warn
    security: info
    boot: info
  org.hibernate:
    SQL: warn
  com.nextree: debug